apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
spec:
  template:
    spec:
      containers:
        - name: migrator
          image: ecommerce-db-migrator:latest
          imagePullPolicy: Always
          env:
            - name: CUSTOMER_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: connection-string
            - name: ORDER_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: connection-string
            - name: PRODUCT_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: connection-string
            - name: BUSINESSEVENT_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: connection-string
      restartPolicy: Never
  backoffLimit: 1
