apiVersion: apps/v1
kind: Deployment
metadata:
  name: modularmonolith
  labels:
    app: modularmonolith
spec:
  replicas: 3
  selector:
    matchLabels:
      app: modularmonolith
  template:
    metadata:
      labels:
        app: modularmonolith
    spec:
      containers:
        - name: modularmonolith
          image: modularmonolith:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_PATHBASE
              value: "/modulith"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: connection-string
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
