apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: modularmonolith-http
spec:
  scaleTargetRef:
    deployment: modularmonolith
    service: modularmonolith
    port: 8080
  replicas:
    min: 1
    max: 10
  triggers:
    - type: http
      metadata:
        targetPendingRequests: "20"

