---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: default
spec:
  encryptedData:
    connection-string: AgA+z1LXMjlmoloIUMVTwY/yvkoc1L1BhhAeQyZD3EDG6l1rnYFy/+VIVCP3l4ojP0aVzLVS6GDknJk7DebuB4LuIFNYL+CVd7cJpMlTZGIKpEjqRyi5Byn/UV1qt95zzTnwl/JyJUH3UHY+3zKL1N6y83KPmyY34iZ+LVc19Yfcud0uciNLsnWx03aG9Vs6DcX4q/145awWdYSQrXKzMratROi/xbgB4oI542zTrQ1MRv9wUpwF4KIrDXf3fzTvuXIBMMHqYTi8QIswltjeGm0xDd60x8xlIHI29BNS6RSJBNcV/62JonTkSFG+kv/jeg5jbijcnAsShr1UFuUC5IjhMi8pBhfBROERtoq+9yDrAUWDL6CETNbWx+U7Tq01HvQgyA4wqB2fKAbBBZUZJRtCKVZac1Vqp+fL/gdGodtesRbDVONEQNH9cdFHIdWwpOsbzW5dYMXrXA+QmIoOMV/edD+5133jAWslALGuUh39cz4dc/VwwDdKb/2WzUXJYMyhelSTNevQFST66YNs/+Sh5kc5c4ZfT2oNakHHaxhNqno+KibzQqf6bQAVzXNZRLpGOiyFEyVojdw4mO907ivaJJpdHH1/yuRjqFfisewjwQE2cmQZryPTV9ceHe7HkB1RmGXRLU+XjxZ+MK1Vz7p+ViU/cQSoCPo9PDHIe1gHio4nWdfqsL/dzyd6avcjJyCswlutQseC4K2Le/eheo4jIx1vq2puHjjQQGABvOTfK76pg66EEwbNXxvleY2QDHigPjVvbKROH8W0lxT8dmSrmXdtLbB/RHuRIv6kxsRE88/VlNSsgF7CCd628+HNYSXEJoKjmR/FglDMG3ET7d4uLSdsTlwT8IBP1qV8B8VRVwkxnrE=
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: default
