apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'ecommerce_user' | base64
  username: ZWNvbW1lcmNlX3VzZXI=
  # echo -n 'ecommerce_password' | base64
  password: ZWNvbW1lcmNlX3Bhc3N3b3Jk
  # echo -n 'ecommerce' | base64
  database: ZWNvbW1lcmNl
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # Base64 encoded connection string
  # echo -n 'Host=postgres-service;Database=ecommerce;Username=ecommerce_user;Password=ecommerce_password;Port=5432' | base64
  connection-string: SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlO0RhdGFiYXNlPWVjb21tZXJjZTtVc2VybmFtZT1lY29tbWVyY2VfdXNlcjtQYXNzd29yZD1lY29tbWVyY2VfcGFzc3dvcmQ7UG9ydD01NDMy
