# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run unit tests and generate results
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger "trx;LogFileName=TestResults.xml" --results-directory ./test-results
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-results/TestResults.xml
    - name: Publish test results in job summary
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        cat ./test-results/TestResults.xml >> $GITHUB_STEP_SUMMARY
      
