name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - prod
      image:
        description: 'Docker image name to deploy'
        required: true
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
      branch:
        description: 'Git branch to deploy from'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Show parameters
        run: |
          echo "Deploying to: ${{ github.event.inputs.environment }}"
          echo "Using image: ${{ github.event.inputs.image }}:${{ github.event.inputs.image_tag }}"

      # Simulate deployment
      - name: Mock deploy
        run: |
          echo "kubectl set image deployment/my-app my-app=${{ github.event.inputs.image }}:${{ github.event.inputs.image_tag }} --dry-run=client"
          # Replace this with your actual deployment steps
